apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 307602032955.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 307602032955.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 1caf43de
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
